name: Deploy to SiteGround
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH (decode key + known_hosts)
        env:
          SG_SSH_PRIVATE_KEY_B64: ${{ secrets.SG_SSH_PRIVATE_KEY_B64 }}
        run: |
          mkdir -p ~/.ssh
          echo "$SG_SSH_PRIVATE_KEY_B64" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 18765 ssh.greenbayappletonexteriorsolutions.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Push main to SiteGround
        env:
          SG_REMOTE: ${{ secrets.SG_REMOTE }}
        run: |
          git remote remove siteground 2>/dev/null || true
          git remote add siteground "$SG_REMOTE"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=yes -i ~/.ssh/id_ed25519' git push siteground main -v

      - name: Sync database from SQL dump
        env:
          SSH_HOST: ssh.greenbayappletonexteriorsolutions.com
          SSH_PORT: "18765"
          SSH_USER: u3100-pdmwtlq9gnso
          DB_NAME: greenabayappletonexteriors
          DB_USER: wp_local
          DB_PASSWORD: 'Westcoast12#'
          DB_SQL_PATH: fkqc46017421287.sql
        run: |
          ssh -o StrictHostKeyChecking=yes -i ~/.ssh/id_ed25519 -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" \
            DB_NAME="$DB_NAME" \
            DB_USER="$DB_USER" \
            DB_PASSWORD="$DB_PASSWORD" \
            DB_SQL_PATH="$DB_SQL_PATH" \
            'bash -s' <<'EOF'
          set -euo pipefail

          cd /home/customer/www/greenbayappletonexteriorsolutions.com/public_html

          if [ ! -f "$DB_SQL_PATH" ]; then
            echo "SQL dump $DB_SQL_PATH not found in $(pwd)" >&2
            exit 1
          fi

          export MYSQL_PWD="$DB_PASSWORD"
          echo "Disabling foreign key checks ..."
          mysql -u "$DB_USER" -D "$DB_NAME" -e 'SET FOREIGN_KEY_CHECKS = 0;'

          mapfile -t tables < <(mysql -u "$DB_USER" -D "$DB_NAME" -Nse 'SHOW TABLES')
          if [ "${#tables[@]}" -gt 0 ]; then
            echo "Dropping existing tables in $DB_NAME ..."
            for table in "${tables[@]}"; do
              mysql -u "$DB_USER" -D "$DB_NAME" -e "DROP TABLE IF EXISTS \`$table\`;" || true
            done
          else
            echo "No tables found in $DB_NAME."
          fi

          echo "Importing SQL dump ..."
          mysql -u "$DB_USER" "$DB_NAME" < "$DB_SQL_PATH"

          echo "Re-enabling foreign key checks ..."
          mysql -u "$DB_USER" -D "$DB_NAME" -e 'SET FOREIGN_KEY_CHECKS = 1;'

          echo "Updating siteurl/home options ..."
          mysql -u "$DB_USER" "$DB_NAME" -e "UPDATE wp_q2x61kxgzj_options SET option_value='https://greenbayappletonexteriorsolutions.com' WHERE option_name IN ('siteurl','home');"

          echo "Replacing localhost URLs ..."
          mysql -u "$DB_USER" "$DB_NAME" -e "UPDATE wp_q2x61kxgzj_options SET option_value = REPLACE(option_value, 'http://localhost/exterior-solutions', 'https://greenbayappletonexteriorsolutions.com');"
          mysql -u "$DB_USER" "$DB_NAME" -e "UPDATE wp_q2x61kxgzj_posts SET post_content = REPLACE(post_content, 'http://localhost/exterior-solutions', 'https://greenbayappletonexteriorsolutions.com');"
          mysql -u "$DB_USER" "$DB_NAME" -e "UPDATE wp_q2x61kxgzj_postmeta SET meta_value = REPLACE(meta_value, 'http://localhost/exterior-solutions', 'https://greenbayappletonexteriorsolutions.com');"

          echo "Clearing caches ..."
          php <<'PHP'
          <?php
          $roots = [
              __DIR__ . '/html/wp-load.php',
              __DIR__ . '/wp-load.php',
          ];

          $load = null;
          foreach ($roots as $candidate) {
              if (file_exists($candidate)) {
                  $load = $candidate;
                  break;
              }
          }

          if (!$load) {
              fwrite(STDERR, "wp-load.php not found in expected locations.\n");
              exit(1);
          }

          require $load;

          if (function_exists('wp_cache_flush')) {
              wp_cache_flush();
          }

          if (function_exists('flush_rewrite_rules')) {
              flush_rewrite_rules(true);
          }
          PHP
          EOF

      - name: Prune CI files on server
        env:
          SSH_HOST: ssh.greenbayappletonexteriorsolutions.com
          SSH_PORT: "18765"
          SSH_USER: u3100-pdmwtlq9gnso
        run: |
          ssh -o StrictHostKeyChecking=yes -i ~/.ssh/id_ed25519 -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" \
            "rm -rf /home/customer/www/greenbayappletonexteriorsolutions.com/public_html/.github"
