name: Deploy to SiteGround

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SITEGROUND_HOST: giowm1239.siteground.biz
      SITEGROUND_PORT: "18765"
      SITEGROUND_USER: u3100-pdmwtlq9gnso
      SITEGROUND_REPO_PATH: /home/customer/www/greenbayappletonexteriorsolutions.com/public_html/
      SITEGROUND_BRANCH: master

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SITEGROUND_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/siteground_key
          chmod 600 ~/.ssh/siteground_key
          ssh-keyscan -p $SITEGROUND_PORT $SITEGROUND_HOST >> ~/.ssh/known_hosts
          cat <<EOF >> ~/.ssh/config
          Host siteground
            HostName $SITEGROUND_HOST
            User $SITEGROUND_USER
            Port $SITEGROUND_PORT
            IdentityFile ~/.ssh/siteground_key
            IdentitiesOnly yes
          EOF

      - name: Configure Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Push to SiteGround remote
        run: |
          REMOTE_URL="ssh://${SITEGROUND_USER}@${SITEGROUND_HOST}:${SITEGROUND_PORT}${SITEGROUND_REPO_PATH}"
          git remote remove siteground || true
          git remote add siteground "$REMOTE_URL"
          git fetch siteground $SITEGROUND_BRANCH || true
          git push --force siteground HEAD:$SITEGROUND_BRANCH
