name: Deploy to SiteGround
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SG_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 18765 ssh.greenbayappletonexteriorsolutions.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      - name: Push to SiteGround
        env:
          SG_REMOTE: ${{ secrets.SG_REMOTE }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git remote | grep -q "^siteground$"; then
            git remote set-url siteground "$SG_REMOTE"
          else
            git remote add siteground "$SG_REMOTE"
          fi
          GIT_SSH_COMMAND='ssh -i ~/.ssh/id_ed25519' git push siteground main
