name: Deploy to SiteGround
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH (key + known_hosts)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SG_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 18765 ssh.greenbayappletonexteriorsolutions.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Push main to SiteGround
        env:
          SG_REMOTE: ${{ secrets.SG_REMOTE }}
        run: |
          git remote remove siteground 2>/dev/null || true
          git remote add siteground "$SG_REMOTE"
          GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=yes -i ~/.ssh/id_ed25519' git push siteground main
